menu:
- {name: 'research', url: '/research'}
- {name: 'teaching', url: '/teaching'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

teaching:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/yaeldavidov'}
#- {icon: 'twitter', link: 'https://twitter.com/paululele'}
#- {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/yael-davidov-42962566'}

contacts:
- {name: 'Yael Davidov', title: 'Graduate Student', department: 'Mathematics', institution: 'Rutgers University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'yd209@math.rutgers.edu', office: 'Science Building 505', image: 'assets/img/contact.jpg'}

email:
- 'yd209@math.rutgers.edu'