menu:
- {name: 'about', url: '/'}
- {name: 'research', url: '/research'}
- {name: 'teaching', url: '/teaching'}
- {name: 'other', url: '/other'}
- {name: 'cv', url: '/cv'}


teaching:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/yaeldavidov'}
#- {icon: 'twitter', link: 'https://twitter.com/paululele'}
#- {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/yael-davidov-42962566'}

contacts:
- {name: 'Yael Davidov', title: 'Assistant Professor', department: 'Mathematics', institution: 'University of Delaware', email: 'ydavidov@udel.edu', office: '', image: 'assets/img/contact.jpeg'}

email:
- 'yd209@math.rutgers.edu'